"""Add General Ledger models - GLAccount and GLTransaction

Revision ID: 61d04a562bec
Revises: fe7061b1ad88
Create Date: 2025-05-26 00:24:13.230978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d04a562bec'
down_revision = 'fe7061b1ad88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_subtype', sa.String(length=100), nullable=True),
    sa.Column('parent_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_control_account', sa.Boolean(), nullable=True),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_accounts_account_code'), 'gl_accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_gl_accounts_id'), 'gl_accounts', ['id'], unique=False)
    op.create_table('gl_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accounting_period_id', sa.Integer(), nullable=False),
    sa.Column('gl_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('debit_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('credit_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('source_module', sa.String(length=50), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['accounting_period_id'], ['accounting_periods.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_transactions_id'), 'gl_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_gl_transactions_reference_number'), 'gl_transactions', ['reference_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gl_transactions_reference_number'), table_name='gl_transactions')
    op.drop_index(op.f('ix_gl_transactions_id'), table_name='gl_transactions')
    op.drop_table('gl_transactions')
    op.drop_index(op.f('ix_gl_accounts_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_account_code'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    # ### end Alembic commands ###
