"""update_inventory_items_add_reorder_fields_and_optional_gl_accounts

Revision ID: 86c0ba98cfd7
Revises: feb957222906
Create Date: 2025-05-30 00:13:25.044132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c0ba98cfd7'
down_revision = 'feb957222906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('reorder_level', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('inventory_items', sa.Column('reorder_quantity', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.alter_column('inventory_items', 'gl_asset_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_items', 'gl_expense_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_items', 'gl_revenue_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_types_id'), 'inventory_transaction_types', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transaction_types_id'), table_name='inventory_transaction_types')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.alter_column('inventory_items', 'gl_revenue_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_items', 'gl_expense_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_items', 'gl_asset_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inventory_items', 'reorder_quantity')
    op.drop_column('inventory_items', 'reorder_level')
    # ### end Alembic commands ###
