"""add_order_entry_models

Revision ID: feb957222906
Revises: 3fbb0f49c23a
Create Date: 2025-05-26 21:45:43.183728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb957222906'
down_revision = '3fbb0f49c23a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
